#!/usr/bin/env bash
set -euo pipefail

STAGE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKFLOW_ROOT="$(cd "${STAGE_DIR}/.." && pwd)"
PIPELINE_ROOT="$(cd "${WORKFLOW_ROOT}/.." && pwd)"

usage() {
  cat <<'USAGE'
Usage:
  init_project.sh --project-root PATH --genome-fasta PATH --reference-gtf PATH \
    --sample-names S1,S2 --group1-name NAME --group1-samples S1 \
    --group2-name NAME --group2-samples S2 [options]

Required:
  --project-root PATH
  --genome-fasta PATH | --genome-fasta-gz PATH
  --reference-gtf PATH
  --sample-names CSV
  --group1-name NAME
  --group1-samples CSV
  --group2-name NAME
  --group2-samples CSV

Input source options, choose at least one:
  --fastq-source-dir PATH
  --cellranger-out-source-dir PATH
  --matrix-source-dir PATH
  --external-matrix-source PATH

Other options:
  --analysis-questions-source PATH   Copy an existing analysis_questions.tsv.
  --spatial-sample-names CSV         Optional ST sample IDs to append to samples.tsv.
  --spatial-bundle-root PATH         Optional root containing one ST bundle directory per ST sample.
  --section-sheet PATH               Optional sections.tsv to copy into metadata/.
  --with-saw                         Use SAW defaults for generated ST sample rows.
  --with-cell2location               Mark generated ST rows as deconvolution-ready candidates.
  --input-standardize-mode MODE      symlink or copy. Default: symlink.
  --cellranger-bin PATH
  --sra-tools-dir PATH
  --activate-server-config yes|no    Rewrite config/server_config.sh to source this project config. Default: no.
  --force                            Overwrite generated config files and managed links.
  -h, --help
USAGE
}

die() {
  echo "[ERROR] $*" >&2
  exit 1
}

info() {
  echo "[INFO] $*" >&2
}

abs_path() {
  local path="$1"
  if [[ -z "${path}" ]]; then
    return 0
  fi
  if [[ "${path}" = /* ]]; then
    printf '%s\n' "${path}"
  else
    printf '%s\n' "$(pwd)/${path}"
  fi
}

abs_existing() {
  local path="$1"
  [[ -e "${path}" ]] || die "Path does not exist: ${path}"
  local dir
  local base
  dir="$(cd "$(dirname "${path}")" && pwd -P)"
  base="$(basename "${path}")"
  printf '%s/%s\n' "${dir}" "${base}"
}

safe_id() {
  local value="$1"
  value="${value// /_}"
  value="$(printf '%s' "${value}" | tr -c 'A-Za-z0-9._-' '_')"
  value="${value##_}"
  value="${value%%_}"
  printf '%s\n' "${value:-value}"
}

split_csv() {
  local raw="$1"
  local item
  raw="${raw//,/ }"
  for item in ${raw}; do
    [[ -n "${item}" ]] && printf '%s\n' "${item}"
  done
}

csv_contains() {
  local needle="$1"
  local csv="$2"
  local item
  while IFS= read -r item; do
    [[ "${item}" == "${needle}" ]] && return 0
  done < <(split_csv "${csv}")
  return 1
}

shell_export() {
  local name="$1"
  local value="$2"
  printf 'export %s=%q\n' "${name}" "${value}"
}

replace_link_or_copy() {
  local src="$1"
  local dst="$2"
  local mode="$3"
  [[ -e "${src}" ]] || die "Source path does not exist: ${src}"
  if [[ -e "${dst}" || -L "${dst}" ]]; then
    if [[ "${FORCE}" != "yes" ]]; then
      die "Refusing to replace existing path without --force: ${dst}"
    fi
    rm -rf "${dst}"
  fi
  mkdir -p "$(dirname "${dst}")"
  if [[ "${mode}" == "copy" ]]; then
    cp -a "${src}" "${dst}"
  else
    ln -s "${src}" "${dst}"
  fi
}

write_project_config() {
  local path="$1"
  {
    echo "# Generated by workflow/03stages/init_project.sh."
    echo "# Edit project-level paths here, then run stages with:"
    echo "#   export SCRNA_PIPELINE_CONFIG=${path}"
    shell_export PROJECT_ROOT "${PROJECT_ROOT}"
    shell_export PIPELINE_ROOT "${PIPELINE_ROOT}"
    shell_export PROJECT_CONFIG_DIR "${PROJECT_CONFIG_DIR}"
    shell_export DATA_DIR "${DATA_DIR}"
    shell_export RESULTS_DIR "${RESULTS_DIR}"
    shell_export CHECKPOINT_DIR "${CHECKPOINT_DIR}"
    shell_export FIGURE_DIR "${FIGURE_DIR}"
    shell_export TABLE_DIR "${TABLE_DIR}"
    shell_export LOG_DIR "${LOG_DIR}"
    shell_export ENV_DIR "${ENV_DIR}"
    shell_export RESOURCE_DIR "${RESOURCE_DIR}"
    shell_export MANIFEST_DIR "${MANIFEST_DIR}"
    shell_export RAW_DIR "${RAW_DIR}"
    shell_export RAW_RECEIVED_DIR "${RAW_RECEIVED_DIR}"
    shell_export METADATA_DIR "${METADATA_DIR}"
    shell_export REPORT_DIR "${REPORT_DIR}"
    shell_export INTAKE_REPORT_DIR "${INTAKE_REPORT_DIR}"
    shell_export EDA_REPORT_DIR "${EDA_REPORT_DIR}"
    shell_export STATUS_DIR "${STATUS_DIR}"
    shell_export WORKFLOW_STATUS_FILE "${WORKFLOW_STATUS_FILE}"
    shell_export REFERENCE_DIR "${REFERENCE_DIR}"
    shell_export REFERENCE_ROOT "$(dirname "${REFERENCE_DIR}")"
    shell_export FASTQ_DIR "${FASTQ_DIR}"
    shell_export GENOME_FASTA_GZ "${GENOME_FASTA_GZ}"
    shell_export REFERENCE_GTF "${REFERENCE_GTF}"
    shell_export CLEAN_GTF "${CLEAN_GTF}"
    shell_export CELLRANGER_OUT_DIR "${CELLRANGER_OUT_DIR}"
    shell_export DNBC4TOOLS_OUT_DIR "${DNBC4TOOLS_OUT_DIR}"
    shell_export SAMPLE_SHEET "${SAMPLE_SHEET}"
    shell_export CANONICAL_SAMPLE_SHEET "${CANONICAL_SAMPLE_SHEET}"
    shell_export COMPARISON_SHEET "${COMPARISON_SHEET}"
    shell_export SECTION_SHEET "${SECTION_SHEET}"
    shell_export SPATIAL_REFERENCE_INVENTORY_FILE "${SPATIAL_REFERENCE_INVENTORY_FILE}"
    shell_export ANALYSIS_QUESTIONS_FILE "${ANALYSIS_QUESTIONS_FILE}"
    shell_export TRAJECTORY_PAIRS_SHEET "${TRAJECTORY_PAIRS_SHEET}"
    shell_export COMMUNICATION_PAIRS_SHEET "${COMMUNICATION_PAIRS_SHEET}"
    shell_export SCENIC_TARGETS_SHEET "${SCENIC_TARGETS_SHEET}"
    shell_export ENRICHMENT_TARGETS_SHEET "${ENRICHMENT_TARGETS_SHEET}"
    shell_export GENE_PROGRAM_TARGETS_SHEET "${GENE_PROGRAM_TARGETS_SHEET}"
    shell_export SCDESIGN3_QUESTION_MAP "${SCDESIGN3_QUESTION_MAP}"
    shell_export SCDESIGN3_TARGETS_SHEET "${SCDESIGN3_TARGETS_SHEET}"
    shell_export SCDESIGN3_SIMULATION_DESIGNS_SHEET "${SCDESIGN3_SIMULATION_DESIGNS_SHEET}"
    shell_export SCDESIGN3_THRESHOLDS_SHEET "${SCDESIGN3_THRESHOLDS_SHEET}"
    shell_export DELIVERY_MANIFEST "${DELIVERY_MANIFEST}"
    shell_export RECEIVED_FILES_MANIFEST "${RECEIVED_FILES_MANIFEST}"
    shell_export INPUT_INVENTORY_FILE "${INPUT_INVENTORY_FILE}"
    shell_export SPATIAL_INPUT_INVENTORY_FILE "${SPATIAL_INPUT_INVENTORY_FILE}"
    shell_export BRANCH_READINESS_FILE "${BRANCH_READINESS_FILE}"
    shell_export INTAKE_SUMMARY_FILE "${INTAKE_SUMMARY_FILE}"
    shell_export WAIVER_FILE "${WAIVER_FILE}"
    shell_export QC_THRESHOLD_FILE "${QC_THRESHOLD_FILE}"
    shell_export SPATIAL_QC_THRESHOLD_FILE "${SPATIAL_QC_THRESHOLD_FILE}"
    shell_export EDA_GATE_FILE "${EDA_GATE_FILE}"
    shell_export OBJECT_LAYER_CONFIG_FILE "${OBJECT_LAYER_CONFIG_FILE}"
    shell_export SPATIAL_OBJECT_LAYER_FILE "${SPATIAL_OBJECT_LAYER_FILE}"
    shell_export SPATIAL_INTAKE_CONTRACT_FILE "${SPATIAL_INTAKE_CONTRACT_FILE}"
    shell_export MARKER_PANEL_DIR "${MARKER_PANEL_DIR}"
    shell_export MITO_GENE_LIST_FILE "${MITO_GENE_LIST_FILE}"
    shell_export AMBIENT_REPORT_DIR "${AMBIENT_REPORT_DIR}"
    shell_export PRE_QC_REPORT_DIR "${PRE_QC_REPORT_DIR}"
    shell_export POST_QC_REPORT_DIR "${POST_QC_REPORT_DIR}"
    shell_export INTEGRATION_REPORT_DIR "${INTEGRATION_REPORT_DIR}"
    shell_export ANNOTATION_REPORT_DIR "${ANNOTATION_REPORT_DIR}"
    shell_export SUBCLUSTER_REPORT_DIR "${SUBCLUSTER_REPORT_DIR}"
    shell_export DEG_REPORT_DIR "${DEG_REPORT_DIR}"
    shell_export ENRICHMENT_REPORT_DIR "${ENRICHMENT_REPORT_DIR}"
    shell_export COMMUNICATION_REPORT_DIR "${COMMUNICATION_REPORT_DIR}"
    shell_export REGULATION_REPORT_DIR "${REGULATION_REPORT_DIR}"
    shell_export TRAJECTORY_REPORT_DIR "${TRAJECTORY_REPORT_DIR}"
    shell_export VELOCITY_REPORT_DIR "${VELOCITY_REPORT_DIR}"
    shell_export ST_ENABLED "${ST_ENABLED}"
    shell_export ST_FANOUT_VERSION "${ST_FANOUT_VERSION:-0}"
    shell_export SPATIAL_RESULTS_DIR "${SPATIAL_RESULTS_DIR}"
    shell_export SPATIAL_CHECKPOINT_DIR "${SPATIAL_CHECKPOINT_DIR}"
    shell_export SPATIAL_FIGURE_DIR "${SPATIAL_FIGURE_DIR}"
    shell_export SPATIAL_TABLE_DIR "${SPATIAL_TABLE_DIR}"
    shell_export SPATIAL_REFERENCE_FREEZE_DIR "${SPATIAL_REFERENCE_FREEZE_DIR}"
    shell_export JOINT_RESULTS_DIR "${JOINT_RESULTS_DIR}"
    shell_export JOINT_CHECKPOINT_DIR "${JOINT_CHECKPOINT_DIR}"
    shell_export JOINT_FIGURE_DIR "${JOINT_FIGURE_DIR}"
    shell_export JOINT_TABLE_DIR "${JOINT_TABLE_DIR}"
    shell_export SPATIAL_PRE_QC_REPORT_DIR "${SPATIAL_PRE_QC_REPORT_DIR}"
    shell_export SPATIAL_POST_QC_REPORT_DIR "${SPATIAL_POST_QC_REPORT_DIR}"
    shell_export SPATIAL_INTEGRATION_REPORT_DIR "${SPATIAL_INTEGRATION_REPORT_DIR}"
    shell_export SPATIAL_REGION_ANNOTATION_REPORT_DIR "${SPATIAL_REGION_ANNOTATION_REPORT_DIR}"
    shell_export SPATIAL_DECONV_REPORT_DIR "${SPATIAL_DECONV_REPORT_DIR}"
    shell_export SPATIAL_NORMALIZATION_VARIANTS_DIR "${SPATIAL_NORMALIZATION_VARIANTS_DIR}"
    shell_export SPATIAL_NORMALIZATION_COMPARE_DIR "${SPATIAL_NORMALIZATION_COMPARE_DIR}"
    shell_export SPATIAL_NORMALIZATION_OVERRIDE_FILE "${SPATIAL_NORMALIZATION_OVERRIDE_FILE}"
    shell_export SPATIAL_DEFAULT_NORMALIZATION_METHOD "${SPATIAL_DEFAULT_NORMALIZATION_METHOD:-m3_sct_v2}"
    shell_export JOINT_TRAJECTORY_REPORT_DIR "${JOINT_TRAJECTORY_REPORT_DIR}"
    shell_export JOINT_COMMUNICATION_REPORT_DIR "${JOINT_COMMUNICATION_REPORT_DIR}"
    shell_export SAMPLE_NAMES "${SAMPLE_NAMES}"
    shell_export RAW_SAMPLES "${RAW_SAMPLES}"
    shell_export RAW_GROUP_1_NAME "${GROUP1_NAME}"
    shell_export RAW_GROUP_1_SAMPLES "${GROUP1_SAMPLES}"
    shell_export RAW_GROUP_2_NAME "${GROUP2_NAME}"
    shell_export RAW_GROUP_2_SAMPLES "${GROUP2_SAMPLES}"
    shell_export ANALYSIS_GROUP_1_NAME "${GROUP1_NAME}"
    shell_export ANALYSIS_GROUP_1_SAMPLES "${GROUP1_SAMPLES}"
    shell_export ANALYSIS_GROUP_2_NAME "${GROUP2_NAME}"
    shell_export ANALYSIS_GROUP_2_SAMPLES "${GROUP2_SAMPLES}"
    shell_export DEG_IDENT_1 "${GROUP1_NAME}"
    shell_export DEG_IDENT_2 "${GROUP2_NAME}"
    shell_export INPUT_STANDARDIZE_MODE "${INPUT_STANDARDIZE_MODE}"
    shell_export PROJECT_INPUT_MODE "${PROJECT_INPUT_MODE}"
    shell_export CELLRANGER_BIN "${CELLRANGER_BIN}"
    shell_export SRA_TOOLS_DIR "${SRA_TOOLS_DIR}"
    shell_export MAIN_THREADS "${MAIN_THREADS:-8}"
    shell_export VELOCYTO_THREADS "${VELOCYTO_THREADS:-${MAIN_THREADS:-8}}"
    shell_export SCVELO_THREADS "${SCVELO_THREADS:-${MAIN_THREADS:-8}}"
    shell_export R_SPATIAL_ENV_PREFIX "${R_SPATIAL_ENV_PREFIX}"
    shell_export PY_SPATIAL_ENV_PREFIX "${PY_SPATIAL_ENV_PREFIX}"
    shell_export PY_SPATIAL_BIN "${PY_SPATIAL_BIN}"
    shell_export PY_SPATIAL_LEGACY_ENV_PREFIX "${PY_SPATIAL_LEGACY_ENV_PREFIX}"
    shell_export PY_CELL2LOCATION_ENV_PREFIX "${PY_CELL2LOCATION_ENV_PREFIX}"
    shell_export PY_SAW_ENV_PREFIX "${PY_SAW_ENV_PREFIX}"
    shell_export R_VALIDATION_ENV_PREFIX "${R_VALIDATION_ENV_PREFIX}"
    shell_export USE_EXISTING_SIF "${USE_EXISTING_SIF:-no}"
    shell_export REFERENCE_VERSION "${REFERENCE_VERSION:-custom_reference}"
    shell_export PIPELINE_LOCALE "${PIPELINE_LOCALE:-C.UTF-8}"
  } > "${path}"
}

write_samples_tsv() {
  local path="$1"
  local sample
  {
    printf 'sample_id\tcondition\tbiological_replicate\ttechnical_replicate\tbatch\tinput_mode\tinput_source\tsource_path\tplatform\tgene_id_type\treference_version\tgroup_id\ttimepoint\ttissue\tchemistry\trun_main\trun_velocity\trun_scenic\tmodality\tsection_id\tchip_id\tbundle_layout\timage_path\trun_spatial\trun_deconv\trun_joint\tnotes\n'
    while IFS= read -r sample; do
      local condition=""
      local group_id=""
      local source_path=""
      local platform="auto"
      local run_velocity="auto"
      if csv_contains "${sample}" "${GROUP1_SAMPLES}"; then
        condition="${GROUP1_NAME}"
        group_id="${GROUP1_NAME}"
      elif csv_contains "${sample}" "${GROUP2_SAMPLES}"; then
        condition="${GROUP2_NAME}"
        group_id="${GROUP2_NAME}"
      else
        die "Sample is not present in either group sample list: ${sample}"
      fi

      case "${PROJECT_INPUT_MODE}" in
        fastq)
          source_path="${FASTQ_SOURCE_LINK}"
          [[ -d "${FASTQ_SOURCE_LINK}/${sample}" ]] && source_path="${FASTQ_SOURCE_LINK}/${sample}"
          platform="10x_cellranger"
          run_velocity="auto"
          ;;
        cellranger_out)
          source_path="${CELLRANGER_OUT_DIR}"
          [[ -d "${CELLRANGER_OUT_DIR}/${sample}" ]] && source_path="${CELLRANGER_OUT_DIR}/${sample}"
          platform="10x_cellranger"
          run_velocity="auto"
          ;;
        matrix)
          source_path="${MATRIX_SOURCE_LINK}"
          [[ -d "${MATRIX_SOURCE_LINK}/${sample}" ]] && source_path="${MATRIX_SOURCE_LINK}/${sample}"
          platform="generic_mex"
          run_velocity="no"
          ;;
      esac

      printf '%s\t%s\t%s\t1\tbatch1\t%s\tinit_project\t%s\t%s\tauto\t%s\t%s\t\t\t\tyes\t%s\tyes\tscrna\t\t\t\t\tno\tno\tno\t\n' \
        "${sample}" "${condition}" "${sample}" "${PROJECT_INPUT_MODE}" "${source_path}" \
        "${platform}" "${REFERENCE_VERSION:-custom_reference}" "${group_id}" "${run_velocity}"
    done < <(split_csv "${SAMPLE_NAMES}")

    if [[ -n "${SPATIAL_SAMPLE_NAMES}" ]]; then
      while IFS= read -r sample; do
        local condition=""
        local group_id=""
        local source_path=""
        local section_id=""
        local chip_id=""
        local platform="visium"
        local bundle_layout="outs_visium"
        local run_deconv="auto"
        [[ -n "${sample}" ]] || continue

        if csv_contains "${sample}" "${GROUP1_SAMPLES}" || [[ "${sample,,}" == *"${GROUP1_NAME,,}"* ]]; then
          condition="${GROUP1_NAME}"
          group_id="${GROUP1_NAME}"
        elif csv_contains "${sample}" "${GROUP2_SAMPLES}" || [[ "${sample,,}" == *"${GROUP2_NAME,,}"* ]]; then
          condition="${GROUP2_NAME}"
          group_id="${GROUP2_NAME}"
        else
          condition="spatial"
          group_id="spatial"
        fi

        source_path="${SPATIAL_BUNDLE_ROOT}"
        [[ -d "${SPATIAL_BUNDLE_ROOT}/${sample}" ]] && source_path="${SPATIAL_BUNDLE_ROOT}/${sample}"
        section_id="$(safe_id "${sample}")"
        chip_id="${section_id}_chip"
        if [[ "${WITH_SAW}" == "yes" ]]; then
          platform="saw"
          bundle_layout="saw_bin50"
        fi
        if [[ "${WITH_CELL2LOCATION}" == "yes" ]]; then
          run_deconv="yes"
        fi

        printf '%s\t%s\t%s\t1\tst_batch1\t%s\tinit_project\t%s\t%s\tauto\t%s\t%s\t\t\t\tno\tno\tno\tspatial\t%s\t%s\t%s\t%s\tyes\t%s\tauto\t\n' \
          "${sample}" "${condition}" "${section_id}" \
          "${platform}_bundle" "${source_path}" "${platform}" "${REFERENCE_VERSION:-custom_reference}" \
          "${group_id}" "${section_id}" "${chip_id}" "${bundle_layout}" \
          "${source_path}/outs/spatial/tissue_lowres_image.png" "${run_deconv}"
      done < <(split_csv "${SPATIAL_SAMPLE_NAMES}")
    fi
  } > "${path}"
}

write_sections_tsv() {
  local path="$1"
  local sample

  if [[ -n "${SECTION_SHEET_SOURCE}" ]]; then
    cp "${SECTION_SHEET_SOURCE}" "${path}"
    return 0
  fi

  {
    printf 'section_id\tchip_id\ttissue_block\tcondition\tplatform\tbundle_root\timage_lowres\timage_hires\ttissue_positions\tscalefactors\tenabled\tnotes\n'
    if [[ -n "${SPATIAL_SAMPLE_NAMES}" ]]; then
      while IFS= read -r sample; do
        local section_id=""
        local chip_id=""
        local condition=""
        local source_path=""
        local platform="visium"
        [[ -n "${sample}" ]] || continue
        section_id="$(safe_id "${sample}")"
        chip_id="${section_id}_chip"
        if csv_contains "${sample}" "${GROUP1_SAMPLES}" || [[ "${sample,,}" == *"${GROUP1_NAME,,}"* ]]; then
          condition="${GROUP1_NAME}"
        elif csv_contains "${sample}" "${GROUP2_SAMPLES}" || [[ "${sample,,}" == *"${GROUP2_NAME,,}"* ]]; then
          condition="${GROUP2_NAME}"
        else
          condition="spatial"
        fi
        [[ "${WITH_SAW}" == "yes" ]] && platform="saw"
        source_path="${DATA_DIR}/${sample}/outs"
        printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\tyes\tGenerated by init_project.\n' \
          "${section_id}" "${chip_id}" "${section_id}_block" "${condition}" "${platform}" \
          "${source_path}" \
          "${source_path}/spatial/tissue_lowres_image.png" \
          "${source_path}/spatial/tissue_hires_image.png" \
          "${source_path}/spatial/tissue_positions_list.csv" \
          "${source_path}/spatial/scalefactors_json.json"
      done < <(split_csv "${SPATIAL_SAMPLE_NAMES}")
    fi
  } > "${path}"
}

write_comparisons_tsv() {
  local path="$1"
  local comparison_id
  comparison_id="$(safe_id "${GROUP1_NAME}_vs_${GROUP2_NAME}")"
  {
    printf 'comparison_id\tsource_question_id\tdisplay_question_id\toutput_alias\treport_title\tlayer_scope\tcontrast_axis\tanalysis_mode\tanalysis_modality\tanalysis_unit\tstat_level\tgroup_var\tident_1\tident_2\tsubset_column\tsubset_value\taggregation_group_var\tcomposition_group_var\tbatch_var\tenabled\tmin_biological_replicates\tforce_exploratory\tmin_cells_per_group\tlogfc_threshold\tproduces_gene_program\tgene_program_role\tnotes\n'
    printf '%s\tD01_condition_DEG\tD01_condition_DEG\tD01_condition_DEG\tCondition DEG\tpanorama\tcondition_split\tcondition_pairwise\tscrna\twhole_layer\tcell_level_exploratory\tcondition\t%s\t%s\t\t\tbiological_replicate\tcondition\tbatch\tyes\t2\tno\t3\t0\tyes\tcondition_deg\tGenerated by init_project.\n' \
      "${comparison_id}" "${GROUP1_NAME}" "${GROUP2_NAME}"
  } > "${path}"
}

write_analysis_questions_tsv() {
  local path="$1"
  if [[ -n "${ANALYSIS_QUESTIONS_SOURCE}" ]]; then
    cp "${ANALYSIS_QUESTIONS_SOURCE}" "${path}"
    return 0
  fi
  {
    printf 'question_id\tquestion_class\tquestion_zh\tscope\tsender_groups\treceiver_groups\tcondition_split\tcontrast_axis\ttools_to_run\tpriority\tstatus\tdepends_on\tnotes\tactivation_policy\tmin_sender_cells\tmin_receiver_cells\tmin_cells_per_condition\tfallback_pair_id\tderived_from_pair_id\tdisplay_question_id\toutput_alias\treport_title\trun_baseline_if_split_fails\n'
    printf 'D01_condition_DEG\tdeg\tCondition DEG\tpanorama\t*\t*\tcondition:%s,%s\tcondition_split\tdeg+enrichment\tP1\tactive\t\tGenerated by init_project.\talways\t\t\t3\t\t\tD01_condition_DEG\tD01_condition_DEG\tCondition DEG\tno\n' \
      "${GROUP1_NAME}" "${GROUP2_NAME}"
  } > "${path}"
}

write_gate_files() {
  local eda_gate_template="${PIPELINE_ROOT}/config/eda_gates.tsv.template"
  [[ -f "${eda_gate_template}" ]] || die "缺少 EDA gate 模板: ${eda_gate_template}"
  if [[ ! -f "${EDA_GATE_FILE}" || "${FORCE}" == "yes" ]]; then
    install -m 0644 "${eda_gate_template}" "${EDA_GATE_FILE}"
  fi
  cat > "${WAIVER_FILE}" <<'EOF'
check_id	scope	reason	approved_by
EOF
  cat > "${QC_THRESHOLD_FILE}" <<'EOF'
sample_id	qc_min_nfeature	qc_min_ncount	qc_min_log10umi	qc_max_mito_pct
__DEFAULT__	200	1000	0.7	20
EOF
  cat > "${OBJECT_LAYER_CONFIG_FILE}" <<'EOF'
layer_id	layer_role	enabled	parent_layer	sample_include	sample_exclude	selection_column	selection_values	rebuild_normalization	hvg_nfeatures	pca_dims	target_clusters	res_range	res_fine_step	normalization_methods	integration_mode	vars_to_regress	description
panorama	panorama	yes					yes	2000	1:30	10	0.10,0.20,0.30,0.40,0.50,0.60,0.80,1.00,1.20	0.005	lognorm	harmony		Root panorama object built from all post-QC cells.
subcluster_1	subcluster	no	panorama					yes	2000	1:20	8	0.10,0.15,0.20,0.25,0.30,0.35,0.40	0.005				Template subcluster row; set sample_include or selection_column/selection_values before enabling.
EOF
  cp -f "${PIPELINE_ROOT}/config/spatial_qc_thresholds.tsv.template" "${SPATIAL_QC_THRESHOLD_FILE}"
  cp -f "${PIPELINE_ROOT}/config/spatial_object_layers.tsv.template" "${SPATIAL_OBJECT_LAYER_FILE}"
  cp -f "${PIPELINE_ROOT}/config/spatial_intake_contract.tsv.template" "${SPATIAL_INTAKE_CONTRACT_FILE}"
  cp -f "${PIPELINE_ROOT}/config/marker_panels/spatial_region_panel.tsv.template" "${MARKER_PANEL_DIR}/spatial_region_panel.tsv.template"
}

write_status_json() {
  cat > "${WORKFLOW_STATUS_FILE}" <<EOF
{
  "generated_by": "workflow/03stages/init_project.sh",
  "project_root": "${PROJECT_ROOT}",
  "pipeline_root": "${PIPELINE_ROOT}",
  "updated_at": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
  "status": {
    "metadata_valid": false,
    "inputs_audited": false,
    "standardized_inputs": false,
    "input_summary_ready": false,
    "velocity_upstream_ready": false,
    "velocity_reference_ready": false
  },
  "eda_gates": {
    "ambient": "pending",
    "pre_qc": "pending",
    "post_qc": "pending",
    "integration": "pending",
    "annotation": "pending",
    "subcluster": "pending",
    "deg": "pending",
    "enrichment": "pending",
    "communication": "pending",
    "regulation": "pending",
    "trajectory_inputs": "pending",
    "trajectory_methods": "pending",
    "trajectory_finalize": "pending",
    "velocity_inputs": "pending",
    "velocity_finalize": "pending",
    "scdesign3_targets": "pending",
    "scdesign3_validated": "pending",
    "spatial_pre_qc": "pending",
    "spatial_post_qc": "pending",
    "spatial_integration": "pending",
    "spatial_region_annotation": "pending",
    "spatial_deconv": "pending",
    "joint_trajectory": "pending",
    "joint_communication": "pending"
  },
  "waivers": []
}
EOF
}

activate_server_config() {
  local server_config="${PIPELINE_ROOT}/config/server_config.sh"
  local backup="${server_config}.backup_$(date +%Y%m%d_%H%M%S)"
  [[ -f "${server_config}" ]] && cp "${server_config}" "${backup}"
  cat > "${server_config}" <<EOF
#!/usr/bin/env bash
# Generated by workflow/03stages/init_project.sh.
# Previous config backup: ${backup}
source "${PROJECT_CONFIG_FILE}"
EOF
  info "Updated ${server_config}; backup: ${backup}"
}

PROJECT_ROOT=""
FASTQ_SOURCE_DIR=""
GENOME_FASTA=""
REFERENCE_GTF_IN=""
SAMPLE_NAMES=""
GROUP1_NAME=""
GROUP1_SAMPLES=""
GROUP2_NAME=""
GROUP2_SAMPLES=""
CELLRANGER_OUT_SOURCE_DIR=""
MATRIX_SOURCE_DIR=""
ANALYSIS_QUESTIONS_SOURCE=""
SPATIAL_SAMPLE_NAMES=""
SPATIAL_BUNDLE_ROOT=""
SECTION_SHEET_SOURCE=""
WITH_SAW="no"
WITH_CELL2LOCATION="no"
CELLRANGER_BIN=""
SRA_TOOLS_DIR=""
INPUT_STANDARDIZE_MODE="symlink"
ACTIVATE_SERVER_CONFIG="no"
FORCE="no"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --project-root) PROJECT_ROOT="$(abs_path "$2")"; shift 2 ;;
    --fastq-source-dir) FASTQ_SOURCE_DIR="$(abs_existing "$2")"; shift 2 ;;
    --genome-fasta|--genome-fasta-gz) GENOME_FASTA="$(abs_existing "$2")"; shift 2 ;;
    --reference-gtf) REFERENCE_GTF_IN="$(abs_existing "$2")"; shift 2 ;;
    --sample-names) SAMPLE_NAMES="$2"; shift 2 ;;
    --group1-name) GROUP1_NAME="$2"; shift 2 ;;
    --group1-samples) GROUP1_SAMPLES="$2"; shift 2 ;;
    --group2-name) GROUP2_NAME="$2"; shift 2 ;;
    --group2-samples) GROUP2_SAMPLES="$2"; shift 2 ;;
    --cellranger-out-source-dir) CELLRANGER_OUT_SOURCE_DIR="$(abs_existing "$2")"; shift 2 ;;
    --matrix-source-dir|--external-matrix-source) MATRIX_SOURCE_DIR="$(abs_existing "$2")"; shift 2 ;;
    --analysis-questions-source) ANALYSIS_QUESTIONS_SOURCE="$(abs_existing "$2")"; shift 2 ;;
    --spatial-sample-names) SPATIAL_SAMPLE_NAMES="$2"; shift 2 ;;
    --spatial-bundle-root) SPATIAL_BUNDLE_ROOT="$(abs_existing "$2")"; shift 2 ;;
    --section-sheet) SECTION_SHEET_SOURCE="$(abs_existing "$2")"; shift 2 ;;
    --with-saw) WITH_SAW="yes"; shift ;;
    --with-cell2location) WITH_CELL2LOCATION="yes"; shift ;;
    --cellranger-bin) CELLRANGER_BIN="$(abs_path "$2")"; shift 2 ;;
    --sra-tools-dir) SRA_TOOLS_DIR="$(abs_path "$2")"; shift 2 ;;
    --input-standardize-mode) INPUT_STANDARDIZE_MODE="$2"; shift 2 ;;
    --activate-server-config) ACTIVATE_SERVER_CONFIG="$2"; shift 2 ;;
    --force) FORCE="yes"; shift ;;
    -h|--help) usage; exit 0 ;;
    *) die "Unknown argument: $1" ;;
  esac
done

[[ -n "${PROJECT_ROOT}" ]] || die "--project-root is required."
[[ -n "${GENOME_FASTA}" ]] || die "--genome-fasta is required."
[[ -n "${REFERENCE_GTF_IN}" ]] || die "--reference-gtf is required."
[[ -n "${SAMPLE_NAMES}" ]] || die "--sample-names is required."
[[ -n "${GROUP1_NAME}" ]] || die "--group1-name is required."
[[ -n "${GROUP1_SAMPLES}" ]] || die "--group1-samples is required."
[[ -n "${GROUP2_NAME}" ]] || die "--group2-name is required."
[[ -n "${GROUP2_SAMPLES}" ]] || die "--group2-samples is required."
[[ "${INPUT_STANDARDIZE_MODE}" == "symlink" || "${INPUT_STANDARDIZE_MODE}" == "copy" ]] || die "--input-standardize-mode must be symlink or copy."
[[ "${ACTIVATE_SERVER_CONFIG}" == "yes" || "${ACTIVATE_SERVER_CONFIG}" == "no" ]] || die "--activate-server-config must be yes or no."

source_count=0
[[ -n "${FASTQ_SOURCE_DIR}" ]] && source_count=$((source_count + 1))
[[ -n "${CELLRANGER_OUT_SOURCE_DIR}" ]] && source_count=$((source_count + 1))
[[ -n "${MATRIX_SOURCE_DIR}" ]] && source_count=$((source_count + 1))
[[ "${source_count}" -gt 0 ]] || die "Provide at least one input source: FASTQ, Cell Ranger output, or matrix source."
if [[ -n "${SPATIAL_SAMPLE_NAMES}" && -z "${SPATIAL_BUNDLE_ROOT}" ]]; then
  die "--spatial-sample-names requires --spatial-bundle-root."
fi

if [[ -n "${MATRIX_SOURCE_DIR}" ]]; then
  PROJECT_INPUT_MODE="matrix"
elif [[ -n "${CELLRANGER_OUT_SOURCE_DIR}" ]]; then
  PROJECT_INPUT_MODE="cellranger_out"
else
  PROJECT_INPUT_MODE="fastq"
fi

while IFS= read -r sample; do
  [[ -n "${sample}" ]] || continue
  if ! csv_contains "${sample}" "${GROUP1_SAMPLES}" && ! csv_contains "${sample}" "${GROUP2_SAMPLES}"; then
    die "Sample ${sample} is not assigned to group1 or group2."
  fi
  if csv_contains "${sample}" "${GROUP1_SAMPLES}" && csv_contains "${sample}" "${GROUP2_SAMPLES}"; then
    die "Sample ${sample} is assigned to both group1 and group2."
  fi
done < <(split_csv "${SAMPLE_NAMES}")

for group_csv in "${GROUP1_SAMPLES}" "${GROUP2_SAMPLES}"; do
  while IFS= read -r sample; do
    [[ -n "${sample}" ]] || continue
    csv_contains "${sample}" "${SAMPLE_NAMES}" || die "Group sample is missing from --sample-names: ${sample}"
  done < <(split_csv "${group_csv}")
done

PROJECT_CONFIG_DIR="${PROJECT_ROOT}/config"
DATA_DIR="${PROJECT_ROOT}/data"
RESULTS_DIR="${PROJECT_ROOT}/results"
CHECKPOINT_DIR="${RESULTS_DIR}/checkpoints"
FIGURE_DIR="${RESULTS_DIR}/figures"
TABLE_DIR="${RESULTS_DIR}/tables"
ST_ENABLED="yes"
SPATIAL_RESULTS_DIR="${RESULTS_DIR}/spatial"
SPATIAL_CHECKPOINT_DIR="${SPATIAL_RESULTS_DIR}/checkpoints"
SPATIAL_FIGURE_DIR="${SPATIAL_RESULTS_DIR}/figures"
SPATIAL_TABLE_DIR="${SPATIAL_RESULTS_DIR}/tables"
SPATIAL_REFERENCE_FREEZE_DIR="${RESULTS_DIR}/spatial_reference_frozen"
JOINT_RESULTS_DIR="${RESULTS_DIR}/joint"
JOINT_CHECKPOINT_DIR="${JOINT_RESULTS_DIR}/checkpoints"
JOINT_FIGURE_DIR="${JOINT_RESULTS_DIR}/figures"
JOINT_TABLE_DIR="${JOINT_RESULTS_DIR}/tables"
LOG_DIR="${PROJECT_ROOT}/logs"
ENV_DIR="${PROJECT_ROOT}/envs"
RESOURCE_DIR="${PROJECT_ROOT}/resources"
MANIFEST_DIR="${RESULTS_DIR}/manifests"
RAW_DIR="${PROJECT_ROOT}/raw"
RAW_RECEIVED_DIR="${RAW_DIR}/received"
METADATA_DIR="${PROJECT_ROOT}/metadata"
REPORT_DIR="${PROJECT_ROOT}/reports"
INTAKE_REPORT_DIR="${REPORT_DIR}/intake"
EDA_REPORT_DIR="${REPORT_DIR}/eda"
STATUS_DIR="${PROJECT_ROOT}/status"
WORKFLOW_STATUS_FILE="${STATUS_DIR}/workflow_status.json"
REFERENCE_DIR="${PROJECT_ROOT}/reference"
FASTQ_DIR="${PROJECT_ROOT}/fastq"
CELLRANGER_OUT_DIR=""
DNBC4TOOLS_OUT_DIR="${DATA_DIR}/dnbc4tools_out"
SAMPLE_SHEET="${METADATA_DIR}/samples.tsv"
CANONICAL_SAMPLE_SHEET="${METADATA_DIR}/samples.canonical.tsv"
COMPARISON_SHEET="${METADATA_DIR}/comparisons.tsv"
SECTION_SHEET="${METADATA_DIR}/sections.tsv"
SPATIAL_REFERENCE_INVENTORY_FILE="${METADATA_DIR}/spatial_reference_inventory.tsv"
ANALYSIS_QUESTIONS_FILE="${METADATA_DIR}/analysis_questions.tsv"
TRAJECTORY_PAIRS_SHEET="${METADATA_DIR}/trajectory_pairs.tsv"
COMMUNICATION_PAIRS_SHEET="${METADATA_DIR}/communication_pairs.tsv"
SCENIC_TARGETS_SHEET="${METADATA_DIR}/scenic_targets.tsv"
ENRICHMENT_TARGETS_SHEET="${METADATA_DIR}/enrichment_targets.tsv"
GENE_PROGRAM_TARGETS_SHEET="${METADATA_DIR}/gene_program_targets.tsv"
SCDESIGN3_QUESTION_MAP="${METADATA_DIR}/scdesign3_question_map.tsv"
SCDESIGN3_TARGETS_SHEET="${METADATA_DIR}/scdesign3_targets.tsv"
SCDESIGN3_SIMULATION_DESIGNS_SHEET="${METADATA_DIR}/scdesign3_simulation_designs.tsv"
SCDESIGN3_THRESHOLDS_SHEET="${METADATA_DIR}/scdesign3_thresholds.tsv"
DELIVERY_MANIFEST="${METADATA_DIR}/delivery_manifest.tsv"
RECEIVED_FILES_MANIFEST="${METADATA_DIR}/received_files_manifest.tsv"
INPUT_INVENTORY_FILE="${INTAKE_REPORT_DIR}/input_inventory.tsv"
SPATIAL_INPUT_INVENTORY_FILE="${INTAKE_REPORT_DIR}/spatial_input_inventory.tsv"
BRANCH_READINESS_FILE="${INTAKE_REPORT_DIR}/branch_readiness.tsv"
INTAKE_SUMMARY_FILE="${INTAKE_REPORT_DIR}/intake_summary.md"
WAIVER_FILE="${PROJECT_CONFIG_DIR}/waivers.tsv"
QC_THRESHOLD_FILE="${PROJECT_CONFIG_DIR}/qc_thresholds.tsv"
SPATIAL_QC_THRESHOLD_FILE="${PROJECT_CONFIG_DIR}/spatial_qc_thresholds.tsv"
EDA_GATE_FILE="${PROJECT_CONFIG_DIR}/eda_gates.tsv"
OBJECT_LAYER_CONFIG_FILE="${PROJECT_CONFIG_DIR}/object_layers.tsv"
SPATIAL_OBJECT_LAYER_FILE="${PROJECT_CONFIG_DIR}/spatial_object_layers.tsv"
SPATIAL_INTAKE_CONTRACT_FILE="${PROJECT_CONFIG_DIR}/spatial_intake_contract.tsv"
MARKER_PANEL_DIR="${PROJECT_CONFIG_DIR}/marker_panels"
MITO_GENE_LIST_FILE="${PROJECT_CONFIG_DIR}/mito_gene_list.txt"
AMBIENT_REPORT_DIR="${EDA_REPORT_DIR}/ambient"
PRE_QC_REPORT_DIR="${EDA_REPORT_DIR}/pre_qc"
POST_QC_REPORT_DIR="${EDA_REPORT_DIR}/post_qc"
INTEGRATION_REPORT_DIR="${EDA_REPORT_DIR}/integration"
ANNOTATION_REPORT_DIR="${EDA_REPORT_DIR}/annotation"
SUBCLUSTER_REPORT_DIR="${EDA_REPORT_DIR}/subcluster"
DEG_REPORT_DIR="${EDA_REPORT_DIR}/deg"
ENRICHMENT_REPORT_DIR="${EDA_REPORT_DIR}/enrichment"
COMMUNICATION_REPORT_DIR="${EDA_REPORT_DIR}/communication"
REGULATION_REPORT_DIR="${EDA_REPORT_DIR}/regulation"
TRAJECTORY_REPORT_DIR="${EDA_REPORT_DIR}/trajectory"
VELOCITY_REPORT_DIR="${EDA_REPORT_DIR}/velocity"
SPATIAL_PRE_QC_REPORT_DIR="${EDA_REPORT_DIR}/spatial_pre_qc"
SPATIAL_POST_QC_REPORT_DIR="${EDA_REPORT_DIR}/spatial_post_qc"
SPATIAL_INTEGRATION_REPORT_DIR="${EDA_REPORT_DIR}/spatial_integration"
SPATIAL_REGION_ANNOTATION_REPORT_DIR="${EDA_REPORT_DIR}/spatial_region_annotation"
SPATIAL_DECONV_REPORT_DIR="${EDA_REPORT_DIR}/spatial_deconv"
SPATIAL_NORMALIZATION_VARIANTS_DIR="${SPATIAL_CHECKPOINT_DIR}/normalization_variants"
SPATIAL_NORMALIZATION_COMPARE_DIR="${REPORT_DIR}/spatial/normalization_compare"
SPATIAL_NORMALIZATION_OVERRIDE_FILE="${PROJECT_CONFIG_DIR}/spatial_normalization_override.tsv"
SPATIAL_DEFAULT_NORMALIZATION_METHOD="${SPATIAL_DEFAULT_NORMALIZATION_METHOD:-m3_sct_v2}"
JOINT_TRAJECTORY_REPORT_DIR="${EDA_REPORT_DIR}/joint_trajectory"
JOINT_COMMUNICATION_REPORT_DIR="${EDA_REPORT_DIR}/joint_communication"
PROJECT_CONFIG_FILE="${PROJECT_CONFIG_DIR}/project_config.sh"
RAW_SAMPLES="${SAMPLE_NAMES}"
REFERENCE_VERSION="${REFERENCE_VERSION:-custom_reference}"
R_SPATIAL_ENV_PREFIX="${ENV_DIR}/conda/r_spatial"
PY_SPATIAL_ENV_PREFIX="${ENV_DIR}/conda/py_spatial"
PY_SPATIAL_BIN="${PY_SPATIAL_ENV_PREFIX}/bin/python"
PY_SPATIAL_LEGACY_ENV_PREFIX="${ENV_DIR}/conda/py_spatial_legacy"
PY_CELL2LOCATION_ENV_PREFIX="${ENV_DIR}/conda/py_cell2location"
PY_SAW_ENV_PREFIX="${ENV_DIR}/conda/py_saw"
R_VALIDATION_ENV_PREFIX="${ENV_DIR}/conda/r_validation"

if [[ -e "${PROJECT_CONFIG_FILE}" && "${FORCE}" != "yes" ]]; then
  die "Project config already exists. Use --force to overwrite generated files: ${PROJECT_CONFIG_FILE}"
fi

mkdir -p \
  "${PROJECT_CONFIG_DIR}" "${DATA_DIR}" "${RESULTS_DIR}" "${CHECKPOINT_DIR}" "${FIGURE_DIR}" \
  "${TABLE_DIR}" "${SPATIAL_RESULTS_DIR}" "${SPATIAL_CHECKPOINT_DIR}" "${SPATIAL_FIGURE_DIR}" \
  "${SPATIAL_TABLE_DIR}" "${SPATIAL_REFERENCE_FREEZE_DIR}" "${JOINT_RESULTS_DIR}" \
  "${JOINT_CHECKPOINT_DIR}" "${JOINT_FIGURE_DIR}" "${JOINT_TABLE_DIR}" \
  "${LOG_DIR}" "${ENV_DIR}" "${RESOURCE_DIR}" "${MANIFEST_DIR}" \
  "${RAW_DIR}" "${RAW_RECEIVED_DIR}" "${METADATA_DIR}" "${REPORT_DIR}" "${INTAKE_REPORT_DIR}" \
  "${EDA_REPORT_DIR}" "${STATUS_DIR}" "${REFERENCE_DIR}" "${MARKER_PANEL_DIR}" \
  "${AMBIENT_REPORT_DIR}" "${PRE_QC_REPORT_DIR}" "${POST_QC_REPORT_DIR}" \
  "${INTEGRATION_REPORT_DIR}" "${ANNOTATION_REPORT_DIR}" "${SUBCLUSTER_REPORT_DIR}" \
  "${DEG_REPORT_DIR}" "${ENRICHMENT_REPORT_DIR}" "${COMMUNICATION_REPORT_DIR}" \
  "${REGULATION_REPORT_DIR}" "${TRAJECTORY_REPORT_DIR}" "${VELOCITY_REPORT_DIR}" \
  "${SPATIAL_PRE_QC_REPORT_DIR}" "${SPATIAL_POST_QC_REPORT_DIR}" \
  "${SPATIAL_INTEGRATION_REPORT_DIR}" "${SPATIAL_REGION_ANNOTATION_REPORT_DIR}" \
  "${SPATIAL_NORMALIZATION_VARIANTS_DIR}" "${SPATIAL_NORMALIZATION_COMPARE_DIR}" \
  "${SPATIAL_DECONV_REPORT_DIR}" "${JOINT_TRAJECTORY_REPORT_DIR}" \
  "${JOINT_COMMUNICATION_REPORT_DIR}" \
  "${DNBC4TOOLS_OUT_DIR}"

GENOME_FASTA_LINK="${REFERENCE_DIR}/$(basename "${GENOME_FASTA}")"
REFERENCE_GTF_LINK="${REFERENCE_DIR}/$(basename "${REFERENCE_GTF_IN}")"
replace_link_or_copy "${GENOME_FASTA}" "${GENOME_FASTA_LINK}" "${INPUT_STANDARDIZE_MODE}"
replace_link_or_copy "${REFERENCE_GTF_IN}" "${REFERENCE_GTF_LINK}" "${INPUT_STANDARDIZE_MODE}"
GENOME_FASTA_GZ="${GENOME_FASTA_LINK}"
REFERENCE_GTF="${REFERENCE_GTF_LINK}"
CLEAN_GTF="${REFERENCE_DIR}/genes.clean.gtf"
replace_link_or_copy "${REFERENCE_GTF_IN}" "${CLEAN_GTF}" "${INPUT_STANDARDIZE_MODE}"

FASTQ_SOURCE_LINK=""
MATRIX_SOURCE_LINK=""
if [[ -n "${FASTQ_SOURCE_DIR}" ]]; then
  replace_link_or_copy "${FASTQ_SOURCE_DIR}" "${FASTQ_DIR}" "${INPUT_STANDARDIZE_MODE}"
  FASTQ_SOURCE_LINK="${FASTQ_DIR}"
else
  mkdir -p "${FASTQ_DIR}"
fi
if [[ -n "${CELLRANGER_OUT_SOURCE_DIR}" ]]; then
  CELLRANGER_OUT_DIR="${RAW_DIR}/cellranger_out"
  replace_link_or_copy "${CELLRANGER_OUT_SOURCE_DIR}" "${CELLRANGER_OUT_DIR}" "${INPUT_STANDARDIZE_MODE}"
fi
if [[ -n "${MATRIX_SOURCE_DIR}" ]]; then
  MATRIX_SOURCE_LINK="${RAW_DIR}/external_matrix_source"
  replace_link_or_copy "${MATRIX_SOURCE_DIR}" "${MATRIX_SOURCE_LINK}" "${INPUT_STANDARDIZE_MODE}"
fi

write_samples_tsv "${SAMPLE_SHEET}"
write_sections_tsv "${SECTION_SHEET}"
write_comparisons_tsv "${COMPARISON_SHEET}"
write_analysis_questions_tsv "${ANALYSIS_QUESTIONS_FILE}"
write_gate_files
write_status_json
write_project_config "${PROJECT_CONFIG_FILE}"

cp -f "${PIPELINE_ROOT}/metadata/spatial_reference_inventory.tsv" "${SPATIAL_REFERENCE_INVENTORY_FILE}"

cat > "${MARKER_PANEL_DIR}/README.md" <<'EOF'
# Marker Panels

Add layer- or tissue-specific marker panels here before running annotation stages.
The metadata generator can also populate this directory from analysis_questions.tsv.
EOF
touch "${MITO_GENE_LIST_FILE}"

if [[ "${ACTIVATE_SERVER_CONFIG}" == "yes" ]]; then
  activate_server_config
fi

info "Project initialized: ${PROJECT_ROOT}"
cat <<EOF

Next steps:
  export SCRNA_PIPELINE_CONFIG="${PROJECT_CONFIG_FILE}"
  bash "${PIPELINE_ROOT}/workflow/03stages/validate_metadata.sh"
  bash "${PIPELINE_ROOT}/workflow/03stages/audit_inputs.sh"
  bash "${PIPELINE_ROOT}/workflow/03stages/standardize_inputs.sh"
  bash "${PIPELINE_ROOT}/workflow/03stages/input_summary.sh"
  bash "${PIPELINE_ROOT}/workflow/03stages/95_run_metadata_generator.sh"
  bash "${PIPELINE_ROOT}/workflow/01run.sh" 00_ortholog
  bash "${PIPELINE_ROOT}/workflow/01run.sh" 01_build_raw

Generated files:
  ${PROJECT_CONFIG_FILE}
  ${SAMPLE_SHEET}
  ${COMPARISON_SHEET}
  ${ANALYSIS_QUESTIONS_FILE}
  ${WORKFLOW_STATUS_FILE}
EOF
