name: velocity
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - scvelo=0.3.2
  - scanpy=1.10.3
  - anndata=0.10.8
  - loompy=3.0.8
  - velocyto.py=0.17.17
  - numpy=1.26
  - scipy=1.11
  - pandas=2.2
  - matplotlib=3.9
  - seaborn=0.13
  - numba=0.60
  - scikit-learn=1.1.2
  - h5py=3.11
  - samtools
  - pip
  - pip:
      - scanorama==1.7.4
      - scrublet==0.2.3
      - palantir
