name: py_cell2location
channels:
  - conda-forge
  - bioconda
  - pytorch
dependencies:
  - python=3.10
  - scanpy=1.10.3
  - anndata=0.10.8
  - numpy=1.26
  - scipy=1.11
  - pandas=2.2
  - matplotlib=3.9
  - seaborn=0.13
  - scikit-learn
  - h5py=3.11
  - pytorch
  - pyro-ppl
  - pip
